language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  app: messenger-back
  api_key:
    secure: xYc3vOfmfBGANpc5w7CebsItlL3VN3cgxAcX84vQ5TGgKEzjzXYv+xZ8rTv8uIl86OAgrH3A2Biixmozcl49/X7Vm7CpzgF3LtcI1WhIOT51R9/jAsIe4UojaXJIvkhuH0FRFh4pGykgsYG1tSb0qmGAyKUdbfNujLCp8cqVxNpi+n31rYyipUZAKOj7IaaWcvyiNXoXYnwys3OviJL1owWnPlypcgyVOXee6ARTEy4hOoX76/zAG5A98GzVWh3ubaQExR8l0OCtqZzGbAmUFc+bgFC2eFxZezYnMRlOV5F/04khkLxytBEGFpKi0vIFlTgBx39PAJzIVTuxGzsGtB7RZUU/cgrpfCWlngpWf1Osnt1Wf7DotXyV9NSoDG/0BFuJbdWUpLPPRH6Nmj1+jDDXVq+Gc8c/y3+LVTdJ3Nv9fLPwczlm9rg3iPUg64Vp5BtSJMM6+mncfiqE/W3YPRoe5eEIJKljsX5JS2W43It6s8X4/ok9a3f+RzyuCNalDjXyNcQMvixZmzt+pUwQPEUjTaQvNYkPy/a2+voq1Hm6HW4/Dy1SOnxa4jopdcLs2v8BJjDbvYTBQ5WhML4fZKEGskUQe29M4yNATPOLHfxbmMAAqa8IinTv3QqkddVeep+keUJUKyCkryXVclvo8RLYbsswdaYnrSsghP3s90A=
